import React, { useEffect } from 'react'
import Navbar from '../components/Navbar'
import { useSelector } from 'react-redux'
import { useNavigate } from 'react-router-dom'
import { motion } from 'motion/react'
import { BsRobot, BsCoin, BsMic, BsArrowRight } from 'react-icons/bs'
import { IoSparkles } from 'react-icons/io5'
import { FaGraduationCap, FaRegCheckCircle, FaChartLine } from 'react-icons/fa'

function Home() {
  const { userData } = useSelector((state) => state.user)
  const navigate = useNavigate()

  useEffect(() => {
    // If logged in, automatically go to dashboard
    if (userData) {
      navigate('/dashboard')
    }
  }, [userData, navigate])

  const features = [
    {
      icon: <IoSparkles size={24} className="text-amber-400" />,
      title: "AI Question Generation",
      desc: "Get personalized technical or behavioral questions tailored strictly to your job role, description, and experience level."
    },
    {
      icon: <BsMic size={24} className="text-emerald-400" />,
      title: "Speech-to-Text Answers",
      desc: "Practice answering vocally. Speak into your microphone, and our built-in speech recognition converts your words to text in real time."
    },
    {
      icon: <FaChartLine size={24} className="text-blue-400" />,
      title: "Analytical AI Feedback",
      desc: "Receive an overall score and comprehensive feedback on what was good, what was missing, and how to improve your answers."
    },
    {
      icon: <FaGraduationCap size={24} className="text-indigo-400" />,
      title: "Ideal Answer Keys",
      desc: "Compare your responses against high-quality, optimal answer guides generated by AI for every single question."
    }
  ]

  return (
    <div className='min-h-screen bg-[#0b0f19] flex flex-col font-sans select-none overflow-x-hidden text-gray-100'>
      <Navbar />

      {/* Hero Section */}
      <main className="flex-1 flex flex-col items-center justify-center text-center px-6 py-20 max-w-5xl mx-auto">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-4 py-1.5 rounded-full text-xs font-semibold tracking-wide flex items-center gap-2 mb-6 shadow-sm shadow-emerald-500/5"
        >
          <BsRobot size={14} className="text-emerald-450" />
          <span>Next-Gen Mock Interviews</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 25 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-white tracking-tight leading-tight max-w-4xl"
        >
          Ace your next job interview with <span className="bg-gradient-to-r from-emerald-400 to-blue-400 bg-clip-text text-transparent">TalentForge AI</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-6 text-base sm:text-lg text-gray-400 max-w-2xl leading-relaxed"
        >
          Generate tailored questions for any job role, speak or type your answers, and receive detailed scoring, qualitative feedback, and ideal answers instantly.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="mt-10 flex flex-col sm:flex-row gap-4 justify-center items-center"
        >
          <button
            onClick={() => navigate('/auth')}
            className="flex items-center gap-2 bg-gradient-to-r from-emerald-500 to-blue-500 hover:opacity-90 text-white font-semibold px-8 py-4 rounded-full transition shadow-lg shadow-emerald-500/10 cursor-pointer text-sm"
          >
            <span>Get Started Free</span>
            <BsArrowRight size={16} />
          </button>
          <a
            href="#features"
            className="text-gray-400 hover:text-white font-semibold px-6 py-4 rounded-full transition cursor-pointer text-sm"
          >
            Learn more
          </a>
        </motion.div>

        {/* Feature Grid */}
        <div id="features" className="mt-32 w-full">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-white">How TalentForge AI Works</h2>
            <p className="text-gray-400 mt-2">A complete framework to build interview confidence</p>
          </div>

          <div className="grid md:grid-cols-2 gap-8 text-left">
            {features.map((feature, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: idx * 0.1 }}
                whileHover={{ y: -5, boxShadow: "0 10px 30px -10px rgba(16, 185, 129, 0.08)", borderColor: "rgba(16, 185, 129, 0.2)" }}
                className="bg-gray-900/40 p-8 rounded-3xl border border-gray-800 shadow-sm transition duration-300"
              >
                <div className="bg-gray-800/80 w-12 h-12 flex items-center justify-center rounded-2xl mb-6 border border-gray-750">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold text-gray-100 mb-2">{feature.title}</h3>
                <p className="text-gray-405 text-sm leading-relaxed text-gray-450">{feature.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-40 border-t border-gray-800 w-full pt-8 text-sm text-gray-500">
          © {new Date().getFullYear()} TalentForge.AI. All rights reserved. Powered by TalentForge AI.
        </div>
      </main>
    </div>
  )
}

export default Home;
